# Generated by Django 3.2.16 on 2023-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20230113_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.IntegerField(choices=[(0, 'Button'), (1, 'Navbar'), (2, 'Card'), (3, 'Miscellaneous')]),
        ),
    ]
