# Generated by Django 3.2.16 on 2023-01-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'Button'), (1, 'Navbar'), (2, 'Card'), (3, 'Miscellaneous')], default=3),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
