# Generated by Django 3.2.16 on 2023-01-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('button', 'button'), ('card', 'card'), ('navbar', 'navbar'), ('loader', 'loader'), ('miscellaneous', 'miscellaneous')], max_length=255),
        ),
    ]
