# Generated by Django 3.2.16 on 2023-01-16 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='forum_favorutes', to=settings.AUTH_USER_MODEL),
        ),
    ]
