# Generated by Django 3.2.16 on 2023-01-22 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0015_rename_favorites_post_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='forum_bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
